defaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
    en:
        languageName: "English"
        contentDir: content/English
    zh:
    	languageName: "中文"
        contentDir: content/Chinese
menu:
	main:
		-identifier: Search
		name: Search
		url: search
		weight: ...
